security:
    encoders:
        Spacestack\Rockly\Domain\User: 'auto'
    providers:
        users:
            entity:
                class: Spacestack\Rockly\Domain\User
                property: 'email'

    firewalls:

        login:
            pattern:  ^/auth/login
            stateless: true
            anonymous: true
            json_login:
                check_path:               /auth/login
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure

        api:
            pattern:   ^/admin
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/,  roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin,  roles: IS_AUTHENTICATED_FULLY }