version: "3"

services:
  nginx:
    image: nginx:latest
    ports: 
      - 8000:8000
    volumes:
      - .:/var/www/rockly
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm.Dockerfile
    volumes:
      - .:/var/www/rockly

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123
    volumes:
      - /tmp/mysql:/var/lib/mysql
    ports:
      - 3307:3306
