version: "3"

services:
  nginx:
    image: nginx:latest
    ports: 
      - 1234:80
    volumes:
      - .:/var/www/rockly
      - ./docker/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - front

  php-fpm:
    build:
      context: .
      dockerfile: ./docker/php-fpm.Dockerfile
    volumes:
      - .:/var/www/rockly

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: 123
    volumes:
      - /tmp/mysql:/var/lib/mysql
    ports:
      - 3307:3306

  redis:
    image: redis:latest

  front:
    build:
      context: .
      dockerfile: ./docker/vue.Dockerfile
    volumes:
      - ./front:/app
    command: ["npm", "run", "serve"]
